version: '3.9'
services:
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=secret
  app:
    build: .
    container_name: test-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
  
    
 